### ISSUE TITLE
Slice Helper Functions Don't Work

### ISSUE THREAD

**Issue by jam1015** [thomasp85/tidygraph#135]
The standard slice function works:

```
library(tidygraph)
iris_clust <- hclust(dist(iris[1:4]))
iris_tree <- as_tbl_graph(iris_clust)
iris_tree <- activate(iris_tree, nodes)
dplyr::slice(iris_tree,c(1,3,5,7))
```

But ```slice_head``` returns an error:

```
dplyr::slice_head(iris_tree, n = 4)
```

as well as other slice helper functions like ```slice_sample```.  Maybe there some trick I'm missing but I think this is fairly basic ```dplyr``` code that should just work.

**Comment by luukvdmeer** [comment]
In tidygraph there is not something like "dplyr code that should just work". The tbl_graph class is a network specific class that subclasses igraph, and not tbl_df or data.frame or similar. Therefore, for every dplyr function, a tbl_graph specific method *has* to be written and added to the package in order to make this function work on tbl_graphs. The slice helper functions are relatively new (introduced in 2020) and a tbl_graph method has not been implemented (yet?).

The function slice itself does have a tbl_graph method. The new helper functions might be convenient, but their output is fortunately quite simple to get with just using slice: `slice(iris_tree, c(1:4))` instead of `slice_head(iris_tree, n = 4)`. Until a slice_head method is implemented we can stick with that.
