### ISSUE TITLE
Cannot set sender and receiver in tbl_graph

### ISSUE THREAD

**Issue by michaellevy** [thomasp85/tidygraph#52]
Regardless of column names or order, I can't seem to set which is the "from" and "to" node in an edgelist.

``` r
suppressPackageStartupMessages({
  library(tidyverse)
  library(tidygraph)
})
el <- tibble(from = c("b", "c"), to = c("a", "b"))
nodes <- tibble(name = letters[1:3])
# Cannot reverse ordering. First edge is a -> b no matter what:
tbl_graph(nodes, el)
#> # A tbl_graph: 3 nodes and 2 edges
#> #
#> # A rooted tree
#> #
#> # Node Data: 3 x 1 (active)
#>    name
#>   <chr>
#> 1     a
#> 2     b
#> 3     c
#> #
#> # Edge Data: 2 x 2
#>    from    to
#>   <int> <int>
#> 1     1     2
#> 2     3     1
tbl_graph(nodes, el[, 2:1])
#> # A tbl_graph: 3 nodes and 2 edges
#> #
#> # A rooted tree
#> #
#> # Node Data: 3 x 1 (active)
#>    name
#>   <chr>
#> 1     a
#> 2     b
#> 3     c
#> #
#> # Edge Data: 2 x 2
#>    from    to
#>   <int> <int>
#> 1     1     2
#> 2     3     1
tbl_graph(nodes, rename(el, from = to, to = from))
#> # A tbl_graph: 3 nodes and 2 edges
#> #
#> # A rooted tree
#> #
#> # Node Data: 3 x 1 (active)
#>    name
#>   <chr>
#> 1     a
#> 2     b
#> 3     c
#> #
#> # Edge Data: 2 x 2
#>    from    to
#>   <int> <int>
#> 1     1     2
#> 2     2     3
# Works with igraph
igraph::graph_from_edgelist(as.matrix(el))
#> IGRAPH ed9b43f DN-- 3 2 -- 
#> + attr: name (v/c)
#> + edges from ed9b43f (vertex names):
#> [1] b->a c->b
igraph::graph_from_edgelist(as.matrix(el[, 2:1]))
#> IGRAPH 1002839 DN-- 3 2 -- 
#> + attr: name (v/c)
#> + edges from 1002839 (vertex names):
#> [1] a->b b->c
```

**Comment by michaellevy** [comment]
Creating the network via `igraph::graph_from_edgelist` and the converting works as expected:

```r
igraph::graph_from_edgelist(as.matrix(el)) %>%
  as_tbl_graph()
```

**Comment by thomasp85** [comment]
Try setting `directed = TRUE` in `tbl_graph`?

**Comment by michaellevy** [comment]
`directed = TRUE` is documented as the default. I confirmed it doesn't change the result.

**Comment by thomasp85** [comment]
Ok - this was a “From-my-phone” suggestion, sorry for leading you astray.

I’ll look into it

**Comment by michaellevy** [comment]
No worries. It's easy enough to create and convert the igraph object, so it's not blocking me. Just fyi.

**Comment by ramorel** [comment]
Problem seems to occur in the `as_graph_node_edge` method when dealing with a tibble. Note first that when using a data frame, the problem does not occur (provided `stringsAsfactors = F`):

```
> el <- data.frame(from = c("b", "c"), to = c("a", "b"), stringsAsFactors = F)
> nodes <- data.frame(name = letters[1:3], stringsAsFactors = F)
> tbl_graph(nodes, el)
# A tbl_graph: 3 nodes and 2 edges
#
# A rooted tree
#
# Node Data: 3 x 1 (active)
  name 
  <chr>
1 a    
2 b    
3 c    
#
# Edge Data: 2 x 2
   from    to
  <int> <int>
1     2     1
2     3     2
```

The issue occurs in the `as_graph_node_edge` when the method evaluates whether the edgelist columns are of class `character`. Currently, the evaluation reads: `if (is.character(edges[, 1]))` and then proceeds to match the edgelist names to the node names. If `edges` is a tibble, this will always evaluate to `false`, since the subset `edges[, 1]` produces a one column tibble and not a vector of characters.

```
> el <- data.frame(from = c("b", "c"), to = c("a", "b"), stringsAsFactors = F)
> class(el[, 1])
[1] "character"
> el <- tibble(from = c("b", "c"), to = c("a", "b"))
> class(el[, 1])
[1] "tbl_df"     "tbl"        "data.frame"
```
As a result, the matching of the names between the edgelist and nodes list does not occur, since `if (is.character(edges[, 1]))` evaluates to `false`. If the evaluation uses double bracket notation-- `if (is.character(edges[[1]]))` -- it evaluates to `true` and the matching occurs.

```
> el <- tibble(from = c("b", "c"), to = c("a", "b"))
> class(el[[1]])
[1] "character"
```

Replacing the single bracket notation for double bracket notation in `as_graph_node_edge` solves the problem.

**Comment by ramorel** [comment]
I have filed a pull request fixing the issue. This is my very first pull request. I hope I have done it well and the request is clear 😬.

**Comment by thomasp85** [comment]
Thanks @ramorel - much appreciated!

The PR was well explained and executed - Congrats on becoming a contributor 🎉
