### ISSUE TITLE
create a comprehensive (network) summary statistic?

### ISSUE THREAD

**Issue by randomgambit** [thomasp85/tidygraph#91]
Hello there! this package is really fantastic!

I wonder if you could add some sort of `network_summary()` function that would provide detailed summary statistics (number of groups, clustering coefficient, average degree, etc) for a given network. Of course, not all of them could/should be computed, but the most important ones could be computed by default.

Like a big picture overview of the most important patterns in the network. That would clearly leverage the strong `igraph` and `networkr` API support that `tidygraph` provides. What do you think?

**Comment by thomasp85** [comment]
I think it would be hard to anticipate what kind of informations is relevant to who, and since some of these summary statistics are slightly time consuming to calculate I think it would be difficult to come up with a sweet spot solution... Is there any reason why you cannot just query whatever you feel is useful by calling the relevant graph algorithms?
